#!/bin/bash

INSTALL_VIMRC="false"
INSTALL_BASH="false"
INSTALL_TMUXCONFIG="false"

#install xcode CL tools
xcode-select --install

#now let's actually install homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

#run brew doctor to make sure everything is installed correctly
brew doctor

#install homebrew cask so we can install other fun things...
brew install caskroom/cask/brew-cask

#install vimrc, bash_profile, and tmux.cong file if the arguments specify
for arg in $@
do
    if [ "$arg" = "-vimrc" ]; then
        INSTALL_VIMRC="true"
    elif [ "$arg" = "-bash" ]; then
        INSTALL_BASH="true"
    elif [ "$arg" = "-tmux" ]; then
       INSTALL_TMUXCONFIG="true" 
    fi
done

if [[ "$INSTALL_VIMRC" = "true" || "$INSTALL_BASH" = "true" || "INSTALL_TMUXCONFIG" = "true" ]]; then
    mkdir ~/tempDir
    git clone https://github.com/zalaby12/vim.git ~/tempDir
    if [ "$INSTALL_BASH" = "true" ]; then
        cp ~/tempDir/.bash_profile ~/
    elif [ "$INSTALL_VIMRC" = "true" ]; then
        cp ~/tempDir/.vimrc ~/
    elif [ "$INSTALL_TMUXCONFIG" = "true" ]; then
        cp ~/tempDir/.tmux.conf ~/
    fi
    rm -rf ~/tempDir
fi

#and any plugins for vim we might need/want, starting with Vundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

#rebuilding vim https://github.com/Valloric/YouCompleteMe/wiki/Building-Vim-from-source
brew install cmake
brew install mercurial
brew install vim

#don't forget youcompleteme!
~/.vim/bundle/YouCompleteMe/./install.py --all

#and finally let's do java, ant, maven, and our coding stuff.

#java first because... well, java...
brew cask install java
java -version #this is to make sure we have the right version

#ant
brew install ant
ant -version

#tmux and setting colors to be right... 
brew install tmux
#git clone .... ~

#maven
brew install maven
mvn -version

#node
brew install node
npm install -g grunt-cli #not sure what this does but the website said to do it...

npm install -g jasmine




